### ISSUE TITLE
Compilation error - ESPHome 2026.6.4

### ISSUE THREAD

**Issue by zagnuts** [mtheli/philips_shaver#12]
Trying to compile on ESPHome 2026.6.4 and am getting an error. The complaint seems to be indicating that:

`static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
`

But I suspect that's a furphy - that setting is in my yaml file, and I had not changed anything other than updating ESPHome. Maybe it's just an issue with my install I need to track down, but have wiped and started fresh, and the error is still there & appears as soon as I add in the external repository. I'll keep checking, but just putting it out there in case something has changed in esphome that has broken things.... not that that *ever* happens. ;-)

The full log from when the compilation errors start is as follows:
```
In file included from src/esphome/components/philips_shaver/bridge.h:4,
                 from src/esphome/components/philips_shaver/bridge.cpp:1:
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const std::string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::philips_shaver::ShaverBridge; Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:35:25:   required from here
   35 |   this->register_service(&ShaverBridge::on_read_characteristic,
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   36 |                           this->svc_name_("ble_read_char"),
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |                           {"service_uuid", "char_uuid"});
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:73:19: note: the comparison reduces to '(116 == 0)'
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const std::string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::philips_shaver::ShaverBridge; Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:44:25:   required from here
   44 |   this->register_service(&ShaverBridge::on_write_characteristic,
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   45 |                           this->svc_name_("ble_write_char"),
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   46 |                           {"service_uuid", "char_uuid", "data"});
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:73:19: note: the comparison reduces to '(116 == 0)'
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const std::string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::philips_shaver::ShaverBridge; Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:47:25:   required from here
   47 |   this->register_service(&ShaverBridge::on_set_throttle,
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   48 |                           this->svc_name_("ble_set_throttle"),
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   49 |                           {"throttle_ms"});
      |                           ~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:73:19: note: the comparison reduces to '(116 == 0)'
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const std::string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::philips_shaver::ShaverBridge; Ts = {}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:50:25:   required from here
   50 |   this->register_service(&ShaverBridge::on_get_info,
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   51 |                           this->svc_name_("ble_get_info"), {});
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:73:19: note: the comparison reduces to '(116 == 0)'
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::register_service(void (T::*)(Ts ...), const std::string&, const std::array<std::__cxx11::basic_string<char>, sizeof... (Ts)>&) [with T = esphome::philips_shaver::ShaverBridge; Ts = {bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:52:25:   required from here
   52 |   this->register_service(&ShaverBridge::on_pair_mode,
      |   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   53 |                           this->svc_name_("ble_pair_mode"),
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |                           {"enabled", "timeout_s"});
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:73:19: error: static assertion failed: register_service() requires 'custom_services: true' in the 'api:' section of your YAML configuration
   73 |         sizeof(T) == 0,
      |         ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:73:19: note: the comparison reduces to '(116 == 0)'
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::fire_homeassistant_event(const std::string&, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&) [with T = void; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/philips_shaver/bridge.cpp:133:33:   required from here
  133 |   this->fire_homeassistant_event(event_type, enriched);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:341:19: warning: invalid application of 'sizeof' to a void type [-Wpointer-arith]
  341 |     static_assert(sizeof(T) == 0, "fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' "
      |                   ^~~~~~~~~
src/esphome/components/api/custom_api_device.h:341:29: error: static assertion failed: fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' section of your YAML configuration
  341 |     static_assert(sizeof(T) == 0, "fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' "
      |                   ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:341:29: note: the comparison reduces to '(1 == 0)'
*** [.pioenvs/ble03/src/esphome/components/philips_shaver/bridge.cpp.o] Error 1
========================= [FAILED] Took 14.89 seconds =========================
```

**Comment by mtheli** [comment]
@zagnuts 
Thank you for your bug report! 

I've tried it on my machine with 2026.6.4 and had no problem. Have you tried to clean the build files before starting a new build?

**Comment by zagnuts** [comment]
I am a muppet. I made too many changes at once - to confirm the issue was not on my side I had done a clean build, but at the same time went and cleaned the code for the device and when I did that I neglected to put back in 
```
api:
  custom_services: true
  homeassistant_services: true
```
doh.

**Comment by mtheli** [comment]
No problem at all — glad the issue resolved itself into thin air. 🙂 Don't hesitate to open another issue if anything looks off, better one report too many than one too few!
